### ISSUE TITLE
Add imports to examples in "Introduction to py5bot"

### ISSUE THREAD

**Issue by kinow** [hx2A/py5book#4]
Hi!

I was reading about the Python mode, but being used to Jupyter notebooks I started searching and found py5. I have a notebook where I can import `py5`, and run the very first example from the docs with no issues.

However, in "Introduction to py5bot", the examples appear to require some imports that are a problem to beginners with no background on the Python mode, processing, or py5.

Would it be possible to have self-contained examples, that can be run individually if copied in a notebook cell? Perhaps that could be useful for building and testing contributions too, to make sure the code runs fine after changes.

Thanks!
Bruno

**Comment by hx2A** [comment]
Hi, @kinow !

> However, in "Introduction to py5bot", the examples appear to require some imports that are a problem to beginners with no background on the Python mode, processing, or py5.

I don't quite follow what you are saying. On the [Introduction to py5bot](http://py5.ixora.io/tutorials/introduction_to_py5bot.html) page there is only one import (`import numpy as np`) towards the end in the "Code Bypass" section. The code bypass can be used to add imports. It would be possible (and perhaps a good idea) to have py5bot import numpy by default on startup, since it is such a commonly used library.

> Would it be possible to have self-contained examples, that can be run individually if copied in a notebook cell?

Sure, it would be great to have more py5bot examples that go beyond what is on the Introduction to py5bot page. That page is intended as a brief explanation of what *could* be done with py5bot and is not itself a comprehensive introduction for beginners. I do need to expand the example code and my priority now that the latest release is done is to put much more content in the [py5examples repo](https://github.com/py5coding/py5examples), which right now is fairly weak.

> Perhaps that could be useful for building and testing contributions too, to make sure the code runs fine after changes.

It happens my plans for unit tests do revolve around using py5bot and jupyter notebooks. Such a thing would be much more effective for py5 than the default Python unittest or pytest type tests.

**Comment by kinow** [comment]
>I don't quite follow what you are saying. On the [Introduction to py5bot](http://py5.ixora.io/tutorials/introduction_to_py5bot.html) page there is only one import (import numpy as np) towards the end in the "Code Bypass" section. The code bypass can be used to add imports. It would be possible (and perhaps a good idea) to have py5bot import numpy by default on startup, since it is such a commonly used library.

Hi, I should have included the steps I had up to the point I tried the code in that page.

1. read the [about page](http://py5.ixora.io/content/about.html)
2. went to the [installation page](http://py5.ixora.io/content/install.html)
3. checked out `py5`, created a new `venv`, `pip install -e .[jupyter]`, followed by `pip install jupyterlab`
4. `jupyter lab --no-browser`
5. copied the ["Quick Example"](http://py5.ixora.io/content/install.html#quick-example) in a new cell
6. it works!

![image](https://user-images.githubusercontent.com/304786/170689892-cd23374a-51bc-4404-b073-b4a71783de0d.png)

I thought I would have to install using Conda, but given I'm just trying it out for the first time, I find `pip` a little faster, and since it worked fine without having to mess with conda environments or kernels, I continued this way.

I also noted that there was a mention that some of the jupyter kernel settings/steps were optional, e.g.

>You can optionally install the py5 Jupyter

7. Found the Tutorial section in the menu, clicked on the ["Introduction"](http://py5.ixora.io/tutorials/introduction_to_py5bot.html) link
8. Copied the first example I saw so that I could read the text and read the code locally to understand what's going on.
9. Code doesn't run.

![image](https://user-images.githubusercontent.com/304786/170690326-ee2a22ce-306b-477f-b356-13c20a3a24ff.png)

10. Added the imports, now it runs but nothing happens

![image](https://user-images.githubusercontent.com/304786/170690428-0eb61025-d564-4f58-9558-8fbf91c3e656.png)

11. Used the very first example, modifying where I pasted the code, fixing imports, and then I was able to reproduce the graph from the docs. But at this point I didn't know if I wanted following the tutorial as the example didn't work, and I wasn't sure if it was worth investing time in py5, or if it'd be better to use the Python mode sans jupyter :disappointed_relieved: 

This was my workflow, and I apologize if I missed some steps in the documentation that would have prevented this issue from happening. I will admit I wasn't reading 100% of the documentation as I was only curious about what were the functionalities of py5, if it took long to run, and learn just the basics on its API.

>Sure, it would be great to have more py5bot examples that go beyond what is on the Introduction to py5bot page. That page is intended as a brief explanation of what could be done with py5bot and is not itself a comprehensive introduction for beginners. I do need to expand the example code and my priority now that the latest release is done is to put much more content in the [py5examples repo](https://github.com/py5coding/py5examples), which right now is fairly weak.

I understand there is a backlog for the project. This issue was more a feedback from a completely beginner. I was browsing my local library, found a book from Processing.py and I remembered a user of Apache Commons Imaging telling me he was using it for extracting metadata in Processing, so I decided to see what Processing is.

You probably have users that know a little more about Processing, or that are familiar with the Python mode already. So this issue is more of a feedback on what could be improved to help complete beginners like myself :slightly_smiling_face: 

>It happens my plans for unit tests do revolve around using py5bot and jupyter notebooks. Such a thing would be much more effective for py5 than the default Python unittest or pytest type tests.

Sounds like a good plan! For a project I worked in the past, we had some unit tests with `pytest`, but for other things it made more sense to write a sort of functional test (bash running the python tool, and coverage.py and merging reports). But we also had doctests in the code and our documentation was created with Sphinx. In our Sphinx project, the examples like the ones from the getting started and intro in py5 were actually Python code imported directly into Sphinx, or self-contained code in the docs.

We found it helpful as pull requests occasionally broke the examples when we added/removed parameters, renamed functions, etc. That saved us time from having users reporting that the examples didn't work, since everything was always built by GH Actions.

But that, of course, increased the workload on the maintainers, and also demanded contributors to fix their PR's if they broke examples. Just food for thought in case that sounds useful :+1: 

And thanks for py5! 

-Bruno

**Comment by hx2A** [comment]
OK, now I see what you have been doing. Interesting to see these steps mapped out like this. It provides insight into the entry points for how a new user approaches py5 and the documentation website. I can use this to make improvements to the website. This is helpful.

> 9. Code doesn't run.

The code didn't run because you are using the regular Python kernel and not the py5bot kernel or the py5 kernel. For that py5bot example code you'd need to install py5bot first, with this:

``` bash
python -m py5jupyter.kernels.py5bot.install --sys-prefix
```

Then create a new Jupyter notebook that uses the py5bot kernel. You'll see py5bot in the upper left corner and not "Python 3 (ipykernel)". The py5bot kernel (and also the py5 kernel) both take care of the function imports for you. You shouldn't ever need to write `from py5 import size`, etc. Any py5 code you see that does not precede every function with `py5.` needs to be executed with something other than the default Python interpreter. There's actually more going on behind the scenes than a simple `from py5 import *`.

> I understand there is a backlog for the project. 

Writing documentation and examples for beginners is an enormous amount of work! We were hoping to be a part of google summer of code and get some help with this but our project was not selected. Nevertheless, progress will continue, one tutorial at a time.

> But that, of course, increased the workload on the maintainers, and also demanded contributors to fix their PR's if they broke examples. Just food for thought in case that sounds useful

Having some kind of unit tests and github actions would take time to setup but once that is done it would save me a lot of time and reduce stress when I do a release! I was planning on creating the unit tests from the examples in the reference documentation. All of that code works and can be re-run to verify that everything continues to work.

> And thanks for py5!

You are welcome!

**Comment by kinow** [comment]
>OK, now I see what you have been doing. Interesting to see these steps mapped out like this. It provides insight into the entry points for how a new user approaches py5 and the documentation website. I can use this to make improvements to the website. This is helpful.

Glad it might be helpful!

>The code didn't run because you are using the regular Python kernel and not the py5bot kernel or the py5 kernel. For that py5bot example code you'd need to install py5bot first, with this:(...)

Ah! That explains it! Will try that next time.

>Writing documentation and examples for beginners is an enormous amount of work! 

Agreed, one of my current tasks at $work is re-writing parts of our documentation with Sphinx, ReadTheDocs, Netlify, and re-organize/re-write the text. 

>We were hoping to be a part of google summer of code and get some help with this but our project was not selected. Nevertheless, progress will continue, one tutorial at a time.

Shame it wasn't accepted this year. I also got a rejection with Jenkins, but next year we were approved. So hopefully you'll get a spot on the next GSoC :crossed_fingers: 

Thanks!
Bruno

p.s.: I'm watching the repo, so I'll continue lurking here, and might bother you again soon when I give py5 another go.

**Comment by hx2A** [comment]
> p.s.: I'm watching the repo, so I'll continue lurking here, and might bother you again soon when I give py5 another go.

Yes, please do!
