### ISSUE TITLE
The 404 page seems to have broken css and links

### ISSUE THREAD

**Issue by villares** [hx2A/py5book#76]
Try this: https://py5coding.org/reference/

Not only the CSS seems broken, but the navigation links on the left are broken too :(

![image](https://user-images.githubusercontent.com/3694604/213887387-24e5b0e5-755b-4709-bdc2-b8275ba368bc.png)

**Comment by hx2A** [comment]
Interesting find.

This is a web server issue. This page delivers the proper 404 page:

http://py5coding.org/nonsense_page.html

This page does not:

http://py5coding.org/nonexistant_dir/nonsense_page.html

When I added this 404 page, which btw happened a week or two ago, I only tested it on top level pages. It didn't occur to me that it would break for a subdirectory page. I'll fix this. Thank you for noticing this.

As an aside, I think http://py5coding.org/reference/ should go to your summary page instead of returning 404.

Before I added the 404 page it would return a horrific looking 403 Authorization Failed error. In the server I added something to change 403 to 404 and return an actual page.

Eventually I'd like to embellish the 404 page, but let's get the CSS stuff working first. :)

**Comment by hx2A** [comment]
@villares while watching a presentation I also fixed the 404 page. Thanks again for noticing the problem.

> Eventually I'd like to embellish the 404 page

The 404's html is now correct but it looks dull. I'd like to jazz it up with perhaps an animated gif. I'll take care of that later.

> As an aside, I think http://py5coding.org/reference/ should go to your summary page instead of returning 404.

I took care of this also. These 3 links now all go to the same page:

* http://py5coding.org/reference/
* http://py5coding.org/reference/index.html
* http://py5coding.org/reference/summary.html
