### ISSUE TITLE
P3D renderer in raspberry pi 4?

### ISSUE THREAD

**Issue by mraeclo** [hx2A/py5book#91]
Hi, how are you? I found out about py5 because I cant use P3D renderer in processing 4 on my raspberry Pi 4.

Im super excited about using something in python and was wondering if py5.P3D renderer in works on rpi 4, does it?

Thanks!

**Comment by hx2A** [comment]
Hi, @mraeclo ! I appreciate your enthusiasm!

Why can't you use the P3D renderer in Processing 4 on a raspberry pi? Is this a hardware limitation? You don't need a GPU to use the OpenGL renderers, but it does help speed things up.

Since py5 is built on top of Processing, the P3D renderer won't work if Processing can't get it to work. I recommend going to the [Processing Discourse](https://discourse.processing.org/) to get more information about Processing and Raspberry Pis. My intuition is that it should work just fine. The Processing Foundation does offer a [Raspberry Pi build](https://processing.org/download) on their download page.

Please let me know what you find out here. If you do get it to work, know that the Thonny editor (which I believe comes pre-installed on the Raspberian OS) has a [py5 plugin](https://github.com/tabreturn/thonny-py5mode) that I think you'll like.

**Comment by mraeclo** [comment]
thanks for the answer. Looked around processing forum and found that the current processing 4 version seems to have an issue with P3D in rpi somehow. Downgraded to 4.0.1 and its working. Will test py5! Thanks!

**Comment by hx2A** [comment]
> Looked around processing forum and found that the current processing 4 version seems to have an issue with P3D in rpi somehow.

Can you send me what you found? I'd like to read this.

> Downgraded to 4.0.1 and its working. Will test py5! Thanks!

Each py5 version contains a specific version of the Processing jars. Conveniently, the latest version of Processing comes with Processing 4.0.1, so you should have no problem with it on you raspberry pi. The next version of py5 most likely will have 4.2, so you'll want to skip that one.

You can find out which version of Processing is being used by comparing py5's release tags with Processing's:

https://github.com/py5coding/py5generator/tags
https://github.com/processing/processing4/tags

The number 1286 in py5's tag is a reference to Processing's tag.

**Comment by mraeclo** [comment]
basically I read this and rolled back my processing version and it worked. 

https://discourse.processing.org/t/error-using-p3d-on-raspberry-pi/40285

I have read more stuff about it but basically once it was solved I stoped caring and forgot haha so I cant really say anything else about this

**Comment by hx2A** [comment]
OK, thank you for the update! Good luck with your projects!

Since you can move forward with what you want to do, I will close this issue.
